### ISSUE TITLE
Why the Extra Config?

### ISSUE THREAD

**Issue by Queuecumber** [aledbf/kube-keepalived-vip#52]
Kubernetes service api (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#servicespec-v1-core) has support for an `externalIPs` flag that seems to indicate exactly what the `vip-configmap` configuration is supposed to be storing. Why use an extra config file instead of that flag?

**Comment by steven-sheehy** [comment]
I'm using kube-keepalived-vip with externalIP myself and it works. It even allows multiple services to bind to the same externalIP. Here's my configmap to make it work (where 10.0.22.150 is my VIP/externalIP):
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived
data:
  10.0.22.150: ""
```
It would be nice if even this minimal configmap wasn't necessary and it used some service annotation, but not a big deal to configure every externalIP one time in the configmap.
